front:
    build: ./front
    ports :
        - "80:80"
    volumes:
        - "./src:/var/www/html"
        - "./logs/apache2:/var/log/apache2"
    links:
        - "engine"
        - "database"
engine:
    build: ./engine
    expose:
        - "9000"
    links:
        - "database"
phpmyadmin:
    image: "corbinu/docker-phpmyadmin"
    ports:
        - "8080:80"
    environment:
        - "MYSQL_USERNAME=root"
        - "MYSQL_PASSWORD=root"
    links:
        - "database:mysql" 
database:
    image: "mysql:latest"
    volumes:
        - "/Users/cedrick/docker/dev/php/data:/var/lib/mysql"
    ports:
        - "3306:3306"
    environment:
        - "MYSQL_ROOT_PASSWORD=root"
        - "MYSQL_DATABASE=bdd"
        - "MYSQL_USER=user"
        - "MYSQL_PASSWORD=secret"